name: build and test

on: [push, pull_request]

jobs:

  job_1:

    name: Build and Test

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: npm install

    - run: npm run lint

    - run: npm run build-production --if-present

    - run: npm test
      env:
        CI: true

  job_2:

    name: Deploy to gh-pages

    needs: job_1

    runs-on: ubuntu-latest

    steps:
      - name: Show branch
        env:
          BRANCH: ${{github.ref}}
        run: echo "$BRANCH"

      - name: Checkout
        uses: actions/checkout@v2.3.1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          persist-credentials: false

      - name: Install and Build
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          npm install
          npm run build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.6.1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .
          CLEAN_EXCLUDE: ['README.md', 'dist', 'docs', 'src', 'test']